# This is a basic workflow to help you get started with Actions

name: fetchRealTimeGFS

# Controls when the workflow will run
on:
  # Triggers the workflow every 30 minutes
  schedule:
    - cron: '5/30 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Starting script fetchRealTimeGFS

      # Set up python
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      # Set up python packages
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          
      # Set up extra step for xarray and cfgrib
      - name: install extra python packages (xarray and grib)
        run: |
          pip install install cfgrib xarray
        
      # execute python script fetchRealTimeGFS.py
      - name: execute python script fetchRealTimeGFS.py
        env:
          KAC_USERNAME: ${{ secrets.KAC_USERNAME }}
          KAC_PASSWORD: ${{ secrets.KAC_PASSWORD }}
        run: python scripts/fetchRealTimeGFS.py
      
      # commit files
      - name: commit files
        run: |
          git config --global http.version HTTP/1.1
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
          
      # push changes
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
